interface LogBody  {
    temperature: number,
    humidity: number,
    co2: number,
    light_intensity: number,
    light_start: string,
    light_stop: string,
    water_ph: number,
    water1_rate: number,
    water2_rate: number,
    water1_start: string,
    water1_stop: string,
    water2_start: string,
    water2_stop: string,
}